name: Suggestion
description: Помогите нам стать лучше
body:
  - type: markdown
    attributes:
      value: |
        Спасибо!
  - type: input
    id: suggestion
    attributes:
      label: Название предложения
      description: Поделитесь своими желаниями
      placeholder:
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Опишите предложение
      description: Как и почему это предложение поможет нам?
      placeholder: Я хочу видеть здесь ... , потому что ...
    validations:
      required: true
