name: Для предложений
description: Помогите нам стать лучше
body:
   - type: input
    id: suggestion
    attributes:
      label: Четкое и сжатое описание проблемы
      description: Сжатое описание
      placeholder: Я всегда расстраиваюсь, когда [...]
    validations:
      required: true
      
   - type: textarea
    id: description
    attributes:
      label: Опишите решение, которое вы хотели бы получить
      description: Четкое и сжатое описание того, что вы хотите, чтобы произошло
      placeholder: Я хочу видеть здесь ... , потому что ...
    validations:
      required: true

    - type: textarea
    id: alternatives
    attributes:
      label: Опишите альтернативы, которые вы рассматривали
      description: Четкое и сжатое описание любых альтернативных механки или фич, которые вы рассматривали
      placeholder: Я считаю, что ... лучше оптимизирован и может заменить ...
    validations:
      required: true

    - type: textarea
    id: context
    attributes:
      label: Дополнительный контекст
      description: Добавьте сюда любой другой контекст или скриншоты о запросе фичи
      placeholder:
    validations:
      required: true
