name: Для предложений
description: Помогите нам стать лучше
body:
  - type: input
    id: suggestion
    attributes:
      label: Название предложения
      description: Сжатое описание
      placeholder:
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Раскройте предложение
      description: Как и почему это предложение поможет нам?
      placeholder: Я хочу видеть здесь ... , потому что ...
    validations:
      required: true
