name: Серверный баг
description: Опишите свою проблему.
labels: ["server"]

body:
  - type: input
    id: name
    attributes:
      label: Краткое название бага
      placeholder: пропал аксолотль..
    validations:
      required: true
    
  - type: textarea
    id: desc
    attributes:
      label: Описание
      placeholder: В чем проблема?
    validations:
      required: true

  - type: input
    id: match-id
    attributes:
      label: Дополнительная информация
      placeholder:
    validations:
      required: true
