name: Баг на сервере
description: Опишите свою проблему.
labels: ["server"]

body:
  - type: input
    id: name
    attributes:
      label: Короткое название
      placeholder: Придумайте имя
    validations:
      required: true
    
  - type: textarea
    id: desc
    attributes:
      label: Описание
      placeholder: В чем проблема?
    validations:
      required: true

  - type: textarea
    id: misc
    attributes:
      label: Дополнительная информация
      placeholder:
    validations:
      required: true
