name: Баг на сервере
description: Опишите свою проблему.
labels: ["server"]

body:
  - type: input
    id: name
    attributes:
      label: Опишите баг
      placeholder: Cжатое описание ошибки
    validations:
      required: true
    
  - type: textarea
    id: desc
    attributes:  
      label: Шаги для воспроизведения поведения
      value: |
       Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
       ...
    validations:
      required: true

  - type: textarea
    id: misc
    attributes:
      label: Дополнительная информация
      placeholder:
    validations:
      required: true
