name: Баг на сервере
description: Опишите свою проблему.
labels: ["server"]

body:
  - type: input
    id: name
    attributes:
      label: Опишите баг
      placeholder: Cжатое описание ошибки
    validations:
      required: true
    
  - type: textarea
    id: desc
    attributes:  
      label: Шаги для воспроизведения поведения
    validations:
      required: true

  - type: textarea
    id: misc
    attributes:
      label: Дополнительная информация
      placeholder:
    validations:
      required: true
