name: notify

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Changed Files
        id: changed_files
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > changed_files.txt

      - name: Filter Markdown Files
        id: filter_md
        run: |
          grep '\.md$' changed_files.txt > md_files.txt
          echo "Filtered Markdown files:"
          cat md_files.txt

      - name: Read Changelog
        id: changelog
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: $(head -n 1 md_files.txt)

      - name: Send Changelog to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "ChangelogBot"
          message: |
            🎉 New Changelog Update!
            **${{ github.event.pull_request.title }}**

            ${{ steps.changelog.outputs.content }}
