name: notify

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Search for specific file
        id: search
        run: |
          file=$(git diff --name-only $(git rev-parse origin/main) ${{ github.event.pull_request.head.sha }} | grep -E 'changelog-*\.md')
          echo "file_name=$file" >> $GITHUB_ENV

      - name: Read Changelog
        id: changelog
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: ${{ env.file_name }}

      - name: Discord Webhook Action
        uses: rguillaume/discord-action-embed@v1.0.4
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          message: ""
          embed: '{ "color": 3447003, "title": "", "description": "${{ steps.read-changelog.outputs.content }}" }'
