name: notify

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Detect file
        id: detect_file
        run: |
          FILE_PATH=$(find . -name '*.md')
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV

      - name: Read Changelog
        id: changelog
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: ${{GITHUB_ENV}}
          
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "${{ steps.changelog.outputs.content }}"
