name: notify

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get Changed Files
        id: changed_files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})"

      - name: Filter Markdown Files
        id: filter_md
        run: |
          echo "::set-output name=md_files::$(echo ${{ steps.changed_files.outputs.files }} | tr ' ' '\n' | grep '.md')"

      - name: Read Changelog
        id: changelog
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: ${{ steps.filter_md.outputs.md_files }}

      - name: Send Changelog to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "ChangelogBot"
          message: |
            🎉 New Changelog Update!
            **${{ github.event.pull_request.title }}**

            ${{ steps.changelog.outputs.content }}
