name: notify

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Read Changelog
        id: changelog
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: changelog.md

      - name: Send Changelog to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#8595a1"
          username: "adskiydro4ila"
          message: |
            New Changelog Update!
            **${{ github.event.pull_request.title }}**

            ${{ steps.changelog.outputs.content }}
