name: notify

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      # - name: Search for specific file
      #   id: search
      #   run: |
      #     file=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E 'changelog-*\.md' || true)
      #     echo "file_name=$file" >> $GITHUB_ENV

      - name: Read Changelog
        id: changelog
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: changelog.md

      - name: Discord Webhook Action
        uses: rguillaume/discord-action-embed@v1.0.4
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          message: ""
          embed: '{ "color": 3447003, "title": "dsaa", "description": "test\n###kse" }'
