name: notify

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Read Changelog
        id: changelog
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: changelog.md

      - name: Discord Webhook Action
        uses: rguillaume/discord-action-embed@v1.0.4
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          message: ""
          embed: '{ "color": 3447003, "title": "${ pull_request.title }", "description": "${ pull_request.body }", "url": "${ pull_request.html_url }" }'
